
# on:
#   push:
#     branches: [ "develop" ]
on:
  push:
    branches:
      - develop
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir gopal
      - run: ls
      
      
